/*MODE FUNCTIONALITY HERE*/

#define NORMAL_FUNCTION         1
#define CALIBRATE_MOTORS_POS        2
#define DISPLAY_MOTORS_VEL      3
#define CALIBRATE_MOTORS_VEL     4





/*SELECT MODE FUNCTIONALITY*/
#define CURRENT_OPERATION_MODE  CALIBRATE_MOTORS_POS

