/*MODE FUNCTIONALITY HERE*/

#define NORMAL_FUNCTION         1
#define CALIBRATE_MOTORS        2
#define DISPLAY_MOTORS_VEL      3





/*SELECT MODE FUNCTIONALITY*/
#define CURRENT_OPERATION_MODE  DISPLAY_MOTORS_VEL

